export const MOVIE_GET_REQUEST='MOVIE_GET_REQUEST';
export const MOVIE_GET_SUCCESS="MOVIE_GET_SUCCESS";
export const MOVIE_GET_FAILED= "MOVIE_GET_FAILED";

// movies search

export const MOVIE_SEARCH_REQUEST='MOVIE_SEARCH_REQUEST';
export const MOVIE_SEARCH_SUCCESS="MOVIE_SEARCH_SUCCESS";
export const MOVIE_SEARCH_FAILED= "MOVIE_SEARCH_FAILED";

// Favorite

export const MOVIE_ADD_FAVORITE_REQUEST='MOVIE_ADD_FAVORITE_REQUEST';
export const MOVIE_ADD_FAVORITE_SUCCESS="MOVIE_ADD_FAVORITE_SUCCESS";
export const MOVIE_ADD_FAVORITE_FAILED= "MOVIE_ADD_FAVORITE_FAILED";

// Watchlist
export const MOVIE_ADD_WATCHLIST_REQUEST='MOVIE_ADD_WATCHLIST_REQUEST';
export const MOVIE_ADD_WATCHLIST_SUCCESS="MOVIE_ADD_WATCHLIST_SUCCESS";
export const MOVIE_ADD_WATCHLIST_FAILED= "MOVIE_ADD_WATCHLIST_FAILED";